/**
 * 6502 Assembly Demos for VERA on Apple II
 * Adapted from X16 Community Demos (https://github.com/X16Community/x16-demo)
 * Supports dynamic Slot assignment (Slot 2 $C200, Slot 4 $C400, etc.)
 */

import { parseAssembly } from "../../utility/assembler"

export interface VeraDemoBinary {
  startAddress: number
  code: string[]
  bytes: number[]
}

const hex = (val: number) => val.toString(16).toUpperCase()

/**
 * Generates the 6502 assembly lines for the VERA 16-Sprite Demo.
 */
export const getVeraSpriteDemoAssembly = (slot = 2, startAddress = 0x2000): string[] => {
  const base = 0xC000 + slot * 0x100

  return [
    ` ORG $${hex(startAddress)}`,
    `VERA_ADDR_L EQU $${hex(base + 0x00)}`,
    `VERA_ADDR_M EQU $${hex(base + 0x01)}`,
    `VERA_ADDR_H EQU $${hex(base + 0x02)}`,
    `VERA_DATA0 EQU $${hex(base + 0x03)}`,
    `VERA_DATA1 EQU $${hex(base + 0x04)}`,
    `VERA_CTRL EQU $${hex(base + 0x05)}`,
    `VERA_IEN EQU $${hex(base + 0x06)}`,
    `VERA_ISR EQU $${hex(base + 0x07)}`,
    `VERA_DC_VIDEO EQU $${hex(base + 0x09)}`,
    `VERA_DC_HSCAL EQU $${hex(base + 0x0A)}`,
    `VERA_DC_VSCAL EQU $${hex(base + 0x0B)}`,
    "NUM_SPRITES EQU 16",
    "START:",
    " LDA #$00",
    " STA VERA_CTRL",
    " LDA #$41",
    " STA VERA_DC_VIDEO",
    " LDA #$00",
    " STA VERA_ADDR_L",
    " LDA #$FA",
    " STA VERA_ADDR_M",
    " LDA #$11",
    " STA VERA_ADDR_H",
    " LDA #$00",
    " STA VERA_DATA0",
    " STA VERA_DATA0",
    " LDA #$FF",
    " STA VERA_DATA0",
    " LDA #$0F",
    " STA VERA_DATA0",
    " LDA #$00",
    " STA VERA_ADDR_L",
    " LDA #$FC",
    " STA VERA_ADDR_M",
    " LDA #$11",
    " STA VERA_ADDR_H",
    " LDX #$00",
    "INIT_SPR_LOOP:",
    " LDA #$00",
    " STA VERA_DATA0",
    " LDA #$08",
    " STA VERA_DATA0",
    " LDA SPR_X_LO,X",
    " STA VERA_DATA0",
    " LDA SPR_X_HI,X",
    " STA VERA_DATA0",
    " LDA SPR_Y_LO,X",
    " STA VERA_DATA0",
    " LDA SPR_Y_HI,X",
    " STA VERA_DATA0",
    " LDA #$0C",
    " STA VERA_DATA0",
    " LDA #$90",
    " STA VERA_DATA0",
    " INX",
    " CPX #NUM_SPRITES",
    " BNE INIT_SPR_LOOP",
    " LDA #$00",
    " STA VERA_ADDR_L",
    " STA VERA_ADDR_M",
    " LDA #$11",
    " STA VERA_ADDR_H",
    " LDX #$00",
    "UPLOAD_SHAPE:",
    " LDA SPRITE_PIXELS,X",
    " STA VERA_DATA0",
    " INX",
    " CPX #64",
    " BNE UPLOAD_SHAPE",
    " LDX #$00",
    "UPDATE_SPRITES:",
    " TXA",
    " ASL",
    " ASL",
    " ASL",
    " CLC",
    " ADC #$02",
    " STA VERA_ADDR_L",
    " LDA #$FC",
    " STA VERA_ADDR_M",
    " LDA #$11",
    " STA VERA_ADDR_H",
    " LDA SPR_X_LO,X",
    " CLC",
    " ADC SPR_SPEED_X,X",
    " STA SPR_X_LO,X",
    " LDA SPR_X_HI,X",
    " ADC #$00",
    " STA SPR_X_HI,X",
    " CMP #$02",
    " BCC X_BOUNDS_OK",
    " BNE RESET_X",
    " LDA SPR_X_LO,X",
    " CMP #$80",
    " BCC X_BOUNDS_OK",
    "RESET_X:",
    " LDA #$00",
    " STA SPR_X_LO,X",
    " STA SPR_X_HI,X",
    "X_BOUNDS_OK:",
    " LDA SPR_X_LO,X",
    " STA VERA_DATA0",
    " LDA SPR_X_HI,X",
    " STA VERA_DATA0",
    " LDA SPR_Y_LO,X",
    " CLC",
    " ADC SPR_SPEED_Y,X",
    " STA SPR_Y_LO,X",
    " LDA SPR_Y_HI,X",
    " ADC #$00",
    " STA SPR_Y_HI,X",
    " CMP #$01",
    " BCC Y_BOUNDS_OK",
    " BNE RESET_Y",
    " LDA SPR_Y_LO,X",
    " CMP #$E0",
    " BCC Y_BOUNDS_OK",
    "RESET_Y:",
    " LDA #$00",
    " STA SPR_Y_LO,X",
    " STA SPR_Y_HI,X",
    "Y_BOUNDS_OK:",
    " LDA SPR_Y_LO,X",
    " STA VERA_DATA0",
    " LDA SPR_Y_HI,X",
    " STA VERA_DATA0",
    " INX",
    " CPX #NUM_SPRITES",
    " BNE UPDATE_SPRITES",
    " RTS",
    "SPRITE_PIXELS:",
    " HEX 0F F0 3F FC 7F FE FF FF",
    " HEX FF FF E7 E7 E7 E7 FF FF",
    " HEX FF FF FF FF 7F FE 3F FC",
    " HEX 1F F8 0F F0 07 E0 03 C0",
    " HEX 01 80 03 C0 07 E0 0F F0",
    " HEX 1F F8 3F FC 7F FE FF FF",
    " HEX FF FF E7 E7 E7 E7 FF FF",
    " HEX FF FF 7F FE 3F FC 0F F0",
    "SPR_X_LO:",
    " HEX D8 2F 6F AB 76 22 81 61 A4 A8 29 1D E4 CF 8C 11",
    "SPR_X_HI:",
    " HEX 01 00 00 01 00 01 01 00 01 01 00 01 01 01 01 00",
    "SPR_Y_LO:",
    " HEX DD DF B6 D8 32 B5 93 EA A4 DB FB A8 0E 9B 8D 53",
    "SPR_Y_HI:",
    " HEX 00 01 00 01 00 00 01 00 00 00 00 00 00 00 00 01",
    "SPR_SPEED_X:",
    " HEX 02 01 02 01 02 01 03 03 04 03 01 02 02 02 04 01",
    "SPR_SPEED_Y:",
    " HEX 04 03 04 04 02 02 01 04 01 03 01 02 03 02 03 01"
  ]
}

/**
 * Generates the 6502 assembly lines for the VERA Mode 7 / 256-Color Bitmap Demo.
 */
export const getVeraMode7DemoAssembly = (slot = 2, startAddress = 0x2000): string[] => {
  const base = 0xC000 + slot * 0x100

  return [
    ` ORG $${hex(startAddress)}`,
    `VERA_ADDR_L EQU $${hex(base + 0x00)}`,
    `VERA_ADDR_M EQU $${hex(base + 0x01)}`,
    `VERA_ADDR_H EQU $${hex(base + 0x02)}`,
    `VERA_DATA0 EQU $${hex(base + 0x03)}`,
    `VERA_DATA1 EQU $${hex(base + 0x04)}`,
    `VERA_CTRL EQU $${hex(base + 0x05)}`,
    `VERA_DC_VIDEO EQU $${hex(base + 0x09)}`,
    `VERA_DC_HSCAL EQU $${hex(base + 0x0A)}`,
    `VERA_DC_VSCAL EQU $${hex(base + 0x0B)}`,
    `VERA_L0_CFG EQU $${hex(base + 0x0D)}`,
    `VERA_L0_MAP EQU $${hex(base + 0x0E)}`,
    `VERA_L0_TILE EQU $${hex(base + 0x0F)}`,
    `VERA_L0_HSC_L EQU $${hex(base + 0x10)}`,
    `VERA_L0_HSC_H EQU $${hex(base + 0x11)}`,
    `VERA_L0_VSC_L EQU $${hex(base + 0x12)}`,
    `VERA_L0_VSC_H EQU $${hex(base + 0x13)}`,
    "START:",
    " LDA #$00",
    " STA VERA_CTRL",
    " LDA #$11",
    " STA VERA_DC_VIDEO",
    " LDA #$40",
    " STA VERA_DC_HSCAL",
    " STA VERA_DC_VSCAL",
    " LDA #$07",
    " STA VERA_L0_CFG",
    " LDA #$00",
    " STA VERA_L0_MAP",
    " STA VERA_L0_TILE",
    " STA VERA_L0_HSC_L",
    " STA VERA_L0_HSC_H",
    " STA VERA_L0_VSC_L",
    " STA VERA_L0_VSC_H",
    " LDA #$00",
    " STA VERA_ADDR_L",
    " LDA #$FA",
    " STA VERA_ADDR_M",
    " LDA #$11",
    " STA VERA_ADDR_H",
    " LDX #$00",
    "LOAD_PALETTE:",
    " LDA PALETTE_DATA,X",
    " STA VERA_DATA0",
    " INX",
    " CPX #32",
    " BNE LOAD_PALETTE",
    " LDA #$00",
    " STA VERA_ADDR_L",
    " STA VERA_ADDR_M",
    " LDA #$10",
    " STA VERA_ADDR_H",
    " LDY #$0A",
    "PAGE_LOOP:",
    " LDX #$00",
    "PIXEL_LOOP:",
    " TXA",
    " AND #$0F",
    " STA VERA_DATA0",
    " INX",
    " BNE PIXEL_LOOP",
    " DEY",
    " BNE PAGE_LOOP",
    " RTS",
    "PALETTE_DATA:",
    " HEX 00 00 00 0F 0F 00 F0 00",
    " HEX FF 00 0F 0F F0 0F FF 0F",
    " HEX 88 08 00 08 08 00 80 00",
    " HEX 88 00 08 08 80 08 88 08"
  ]
}

/**
 * Builds executable binary and disassembly for a given VERA demo.
 */
export const buildVeraDemo = (
  generator: (slot: number, start: number) => string[],
  slot = 2,
  startAddress = 0x2000
): VeraDemoBinary => {
  const code = generator(slot, startAddress)
  const bytes = parseAssembly(startAddress, code)
  return {
    startAddress,
    code,
    bytes
  }
}
