export const diskImages: DiskCollectionItem[] = [
  {
    title: "Aztec",
    diskUrl: "Aztec.po",
    imageUrl: new URL("/disks/Aztec.png", window.location.origin),
    type: undefined,
    lastUpdated: new Date(0),
  },
  {
    title: "Eamon",
    diskUrl: "Eamon%201.po",
    imageUrl: new URL("/disks/Eamon%201.png", window.location.origin),
    detailsUrl: new URL("https://eamon.wiki/Source:Eamon_Player%27s_Manual_(revised)"),
    type: undefined,
    lastUpdated: new Date(0),
  },
  {
    title: "Apple IIe Diagnostic",
    diskUrl: "Apple IIe Diagnostic 2.1.po",
    imageUrl: new URL("/disks/Apple IIe Diagnostic 2.1.png", window.location.origin),
    type: undefined,
    lastUpdated: new Date(0),
  },
  {
    title: "MECC Inspector",
    diskUrl: "MECC-Inspector.woz",
    imageUrl: new URL("/disks/MECC-Inspector.png", window.location.origin),
    type: undefined,
    lastUpdated: new Date(0),
  },
  {
    title: "MousePaint",
    diskUrl: "MousePaint.woz",
    imageUrl: new URL("/disks/MousePaint.png", window.location.origin),
    type: undefined,
    lastUpdated: new Date(0),
    params: "color=white",
  },
  {
    title: "Nox Archaist Demo",
    diskUrl: "Nox%20Archaist%20Demo.hdv",
    imageUrl: new URL("/disks/Nox%20Archaist%20Demo.png", window.location.origin),
    detailsUrl: new URL("https://noxarchaist.com"),
    type: undefined,
    lastUpdated: new Date(0),
  },
  {
    title: "Olympic Decathalon",
    diskUrl: "Olympic%20Decathlon.woz",
    imageUrl: new URL("/disks/Olympic%20Decathlon.png", window.location.origin),
    detailsUrl: new URL("https://archive.org/details/microsoft-olympic-decathlon-a2-ph/"),
    type: undefined,
    lastUpdated: new Date(0),
  },
  {
    title: "Print Shop Color",
    diskUrl: "Print%20Shop%20Color.woz",
    imageUrl: new URL("/disks/Print%20Shop%20Color.png", window.location.origin),
    type: undefined,
    lastUpdated: new Date(0),
  },
  {
    title: "ProDOS 2.4.3",
    diskUrl: "ProDOS%202.4.3.po",
    imageUrl: new URL("/disks/ProDOS%202.4.3.png", window.location.origin),
    detailsUrl: new URL("https://prodos8.com/"),
    type: undefined,
    lastUpdated: new Date(0),
  },
  {
    title: "Robotron",
    diskUrl: "Robotron4Joy.po",
    imageUrl: new URL("/disks/Robotron4Joy.png", window.location.origin),
    detailsUrl: new URL("https://groups.google.com/g/comp.sys.apple2/c/2xlihijn82o/"),
    type: undefined,
    lastUpdated: new Date(0),
  },
  {
    title: "Total Replay",
    diskUrl: "Total%20Replay.hdv",
    imageUrl: new URL("/disks/Total%20Replay.png", window.location.origin),
    detailsUrl: new URL("https://archive.org/details/TotalReplay"),
    type: undefined,
    lastUpdated: new Date(0),
  },
  {
    title: "Instant Replay",
    diskUrl: "Instant%20Replay.hdv",
    imageUrl: new URL("/disks/Instant%20Replay.png", window.location.origin),
    detailsUrl: new URL("https://github.com/a2-4am/4sports"),
    type: undefined,
    lastUpdated: new Date(0),
  },
  {
    title: "Pitch Dark",
    diskUrl: "Pitch%20Dark.hdv",
    imageUrl: new URL("/disks/Pitch%20Dark.png", window.location.origin),
    detailsUrl: new URL("https://archive.org/details/PitchDark"),
    type: undefined,
    lastUpdated: new Date(0),
  },
  {
    title: "Ultima IV",
    diskUrl: "Ultima%20IV.hdv",
    imageUrl: new URL("/disks/Ultima%20IV.png", window.location.origin),
    detailsUrl: new URL("https://wiki.ultimacodex.com/wiki/Ultima_IV:_Quest_of_the_Avatar"),
    type: undefined,
    lastUpdated: new Date(0),
  },
  {
    title: "Ultima V",
    diskUrl: "Ultima%20V.hdv",
    imageUrl: new URL("/disks/Ultima%20V.png", window.location.origin),
    detailsUrl: new URL("https://wiki.ultimacodex.com/wiki/Ultima_V:_Warriors_of_Destiny"),
    type: undefined,
    lastUpdated: new Date(0),
  },
  {
    title: "Wizardy Replay v1.1",
    diskUrl: "Wizard%20Replay%20v1.1.hdv",
    imageUrl: new URL("/disks/Wizard%20Replay%20v1.1.png", window.location.origin),
    detailsUrl: new URL("https://archive.org/details/WizardReplay"),
    type: undefined,
    lastUpdated: new Date(0),
    }
    ]