export const diskImages: DiskCollectionItem[] = [
  {
    title: "Aztec",
    diskUrl: "Aztec.po",
    imageUrl: "disks/Aztec.png",
    type: undefined,
    lastUpdated: new Date(0),
  },
  {
    title: "Eamon",
    diskUrl: "Eamon%201.po",
    imageUrl: "disks/Eamon%201.png",
    detailsUrl: "https://eamon.wiki/Source:Eamon_Player%27s_Manual_(revised)",
    type: undefined,
    lastUpdated: new Date(0),
  },
  {
    title: "Apple IIe Diagnostic",
    diskUrl: "Apple IIe Diagnostic 2.1.po",
    imageUrl: "disks/Apple IIe Diagnostic 2.1.png",
    type: undefined,
    lastUpdated: new Date(0),
  },
  {
    title: "MECC Inspector",
    diskUrl: "MECC-Inspector.woz",
    imageUrl: "disks/MECC-Inspector.png",
    type: undefined,
    lastUpdated: new Date(0),
  },
  {
    title: "MousePaint",
    diskUrl: "MousePaint.woz",
    imageUrl: "disks/MousePaint.png",
    type: undefined,
    lastUpdated: new Date(0),
    params: "color=white",
  },
  {
    title: "Nox Archaist Demo",
    diskUrl: "Nox%20Archaist%20Demo.hdv",
    imageUrl: "disks/Nox%20Archaist%20Demo.png",
    detailsUrl: "https://noxarchaist.com",
    type: undefined,
    lastUpdated: new Date(0),
  },
  {
    title: "Olympic Decathalon",
    diskUrl: "Olympic%20Decathlon.woz",
    imageUrl: "disks/Olympic%20Decathlon.png",
    detailsUrl: "https://archive.org/details/microsoft-olympic-decathlon-a2-ph/",
    type: undefined,
    lastUpdated: new Date(0),
  },
  {
    title: "Print Shop Color",
    diskUrl: "Print%20Shop%20Color.po",
    imageUrl: "disks/Print%20Shop%20Color.png",
    type: undefined,
    lastUpdated: new Date(0),
  },
  {
    title: "ProDOS 2.4.3",
    diskUrl: "ProDOS%202.4.3.po",
    imageUrl: "disks/ProDOS%202.4.3.png",
    detailsUrl: "https://prodos8.com/",
    type: undefined,
    lastUpdated: new Date(0),
  },
  {
    title: "Robotron",
    diskUrl: "Robotron4Joy.po",
    imageUrl: "disks/Robotron4Joy.png",
    detailsUrl: "https://groups.google.com/g/comp.sys.apple2/c/2xlihijn82o/",
    type: undefined,
    lastUpdated: new Date(0),
  },
  {
    title: "Total Replay",
    diskUrl: "https://archive.org/download/TotalReplay/Total%20Replay%20v5.2.hdv",
    imageUrl: "disks/Total%20Replay.png",
    detailsUrl: "https://archive.org/details/TotalReplay",
    type: undefined,
    lastUpdated: new Date(0),
  },
  {
    title: "Instant Replay",
    diskUrl: "https://archive.org/download/TotalReplay2/Total%20Replay%20II%20v1.0-alpha.4.hdv",
    imageUrl: "disks/Instant%20Replay.png",
    detailsUrl: "https://github.com/a2-4am/4sports",
    type: undefined,
    lastUpdated: new Date(0),
  },
  {
    title: "Pitch Dark",
    diskUrl: "https://archive.org/download/PitchDark/00playable.hdv",
    imageUrl: "disks/Pitch%20Dark.png",
    detailsUrl: "https://archive.org/details/PitchDark",
    type: undefined,
    lastUpdated: new Date(0),
  },
  {
    title: "Ultima IV",
    diskUrl: "Ultima%20IV.hdv",
    imageUrl: "disks/Ultima%20IV.png",
    detailsUrl: "https://wiki.ultimacodex.com/wiki/Ultima_IV:_Quest_of_the_Avatar",
    type: undefined,
    lastUpdated: new Date(0),
  },
  {
    title: "Ultima V",
    diskUrl: "Ultima%20V.hdv",
    imageUrl: "disks/Ultima%20V.png",
    detailsUrl: "https://wiki.ultimacodex.com/wiki/Ultima_V:_Warriors_of_Destiny",
    type: undefined,
    lastUpdated: new Date(0),
  },
  {
    title: "Wizard Replay",
    diskUrl: "https://archive.org/download/WizardReplay/Wizard%20Replay%20v2.0.hdv",
    imageUrl: "disks/WizardReplay.png",
    detailsUrl: "https://archive.org/details/WizardReplay",
    type: undefined,
    lastUpdated: new Date(0),
    }
    ]