// Auto-generated from 4cade v6.0.1
// 502 games keyed by display name for title-based matching.
// Generated by regen_db.ts

export type FourCadeEntry = {
  disk: string       // .po filename without extension (for GitHub fetch)
  prelaunch: string  // prelaunch .a filename without extension (for GitHub fetch)
}

export const FOUR_CADE_PRELAUNCH_DB: Record<string, FourCadeEntry> = {
  "A E": { disk: "a.e. PRODOS (san inc crack)", prelaunch: "a.e" },
  "Aerial": { disk: "aerial 8k file PRODOS (san inc pack)", prelaunch: "aerial" },
  "Aeronaut": { disk: "aeronauts 17k file PRODOS (san inc pack)", prelaunch: "aeronauts" },
  "Agent U S A": { disk: "agent usa 21k file PRODOS (san inc pack)", prelaunch: "agent.u.s.a" },
  "Airheart": { disk: "airheart PRODOS (san inc crack)", prelaunch: "airheart" },
  "Alcazar": { disk: "alcazar 26k file PRODOS (san inc pack)", prelaunch: "alcazar" },
  "Alf: The First Adventure": { disk: "alf PRODOS (san inc pack)", prelaunch: "alf" },
  "Alien Ambush": { disk: "alien ambush 7k file PRODOS (san inc crack)", prelaunch: "alien.ambush" },
  "Alien Downpour": { disk: "alien downpour 19k file PRODOS (san inc pack)", prelaunch: "alien.downpour" },
  "Alien Lander": { disk: "alien lander PRODOS (san inc pack)", prelaunch: "alien.lander" },
  "Alien Munchies": { disk: "alien munchies 6k file PRODOS (san inc pack)", prelaunch: "alien.munchies" },
  "Alien Typhoon": { disk: "alien typhoon 19k file PRODOS (san inc crack)", prelaunch: "alien.typhoon" },
  "Aliens": { disk: "aliens PRODOS (san inc pack)", prelaunch: "aliens" },
  "Angel-1": { disk: "angel-1 12k file PRODOS (san inc pack)", prelaunch: "angel-1" },
  "Angry Birds": { disk: "angrybirds 27k file 6502 PRODOS (san inc pack)", prelaunch: "angrybirds" },
  "Ankh": { disk: "ankh 17k file PRODOS (san inc crack)", prelaunch: "ankh" },
  "AntiAir": { disk: "antiair (4am pack)", prelaunch: "antiair" },
  "Ape Escape": { disk: "ape escape 21k file PRODOS (san inc pack)", prelaunch: "ape.escape" },
  "Apple Cider Spider": { disk: "apple cider spider PRODOS (san inc pack)", prelaunch: "cider.spider" },
  "Apple Invader": { disk: "apple invader 6k file PRODOS (san inc pack)", prelaunch: "apple.invader" },
  "Apple Panic": { disk: "apple panic 12k file PRODOS (san inc pack)", prelaunch: "apple.panic" },
  "Apple Zap": { disk: "apple zap 9k file PRODOS (san inc pack)", prelaunch: "apple.zap" },
  "Apple-Oids": { disk: "apple-oids 5k file PRODOS (san inc crack)", prelaunch: "apple-oids" },
  "Applz": { disk: "applz 5k file PRODOS (san inc pack)", prelaunch: "applz" },
  "Aquatron": { disk: "aquatron PRODOS (san inc pack)", prelaunch: "aquatron" },
  "Arcade Boot Camp": { disk: "arcade boot camp PRODOS (san inc pack)", prelaunch: "arcade.bt.camp" },
  "Arctic Fox": { disk: "arctic fox PRODOS (san inc pack)", prelaunch: "arctic.fox" },
  "Ardy the Aardvark": { disk: "ardy the aardvark 20k file PRODOS (san inc pack)", prelaunch: "ardy.aardvark" },
  "Arena": { disk: "arena 12k file PRODOS (san inc pack)", prelaunch: "arena" },
  "Argos": { disk: "argos PRODOS (san inc pack)", prelaunch: "argos" },
  "Arkanoid": { disk: "arkanoid PRODOS (san inc pack)", prelaunch: "arkanoid" },
  "Artesians": { disk: "artesians PRODOS (san inc pack)", prelaunch: "artesians" },
  "Ascend": { disk: "ascend 6k file PRODOS (san inc pack)", prelaunch: "ascend" },
  "Asteroid Blaster": { disk: "asteroid blaster 6k file PRODOS (san inc pack)", prelaunch: "asteroid.blastr" },
  "Awass": { disk: "awass 7k file PRODOS (san inc pack)", prelaunch: "awass" },
  "Axis Assassin": { disk: "axis assassin 20k file PRODOS (san inc pack)", prelaunch: "axis.assassin" },
  "Aztec": { disk: "aztec PRODOS (san inc crack)(4cade compatible)", prelaunch: "aztec" },
  "Bad Dudes": { disk: "bad dudes PRODOS (san inc pack)", prelaunch: "bad.dudes" },
  "Ballblazer": { disk: "ballblazer 13k file PRODOS (san inc crack)", prelaunch: "ballblazer" },
  "Bandits": { disk: "bandits PRODOS (san inc crack)", prelaunch: "bandits" },
  "Batman": { disk: "batman PRODOS (san inc pack)", prelaunch: "batman" },
  "Bats in the Belfry": { disk: "bats in the belfry 12k file PRODOS (san inc pack)", prelaunch: "standard" },
  "Battle Cruiser": { disk: "battle cruiser 13k file PRODOS (san inc pack)", prelaunch: "battle.cruiser" },
  "Battlezone": { disk: "battlezone 17k file PRODOS (san inc pack)", prelaunch: "battlezone" },
  "Battlot": { disk: "battlot 7k file PRODOS (san inc pack)", prelaunch: "battlot" },
  "BC's Quest for Tires": { disk: "bc's quest for tires PRODOS (san inc pack)", prelaunch: "bcs.quest" },
  "Beach Landing": { disk: "beach landing PRODOS (san inc pack)", prelaunch: "beach.landing" },
  "Beach-Head": { disk: "beach-head PRODOS (san inc crack)", prelaunch: "beach.head" },
  "Beach-Head II": { disk: "beach-head ii PRODOS (san inc pack)", prelaunch: "beach.head.ii" },
  "Beer Run": { disk: "beer run PRODOS (san inc pack)", prelaunch: "beer.run" },
  "Bellhop": { disk: "bellhop 4k file PRODOS (san inc pack)", prelaunch: "bellhop" },
  "Berzap": { disk: "berzap PRODOS (san inc pack)", prelaunch: "berzap" },
  "Beyond Castle Wolfenstein": { disk: "beyond castle wolfenstein PRODOS (san inc pack)", prelaunch: "beyond.wolfen" },
  "Bezare": { disk: "bezare 13k file PRODOS (san inc pack)", prelaunch: "bezare" },
  "Bezoff": { disk: "bezoff 13k file PRODOS (san inc pack)", prelaunch: "bezoff" },
  "Bill Budge's Trilogy": { disk: "budgetrilogy 11k file PRODOS (san inc pack)", prelaunch: "budgetrilogy" },
  "Black Magic": { disk: "black magic PRODOS (san inc pack)", prelaunch: "black.magic" },
  "Blister Ball": { disk: "blister ball 4k file PRODOS (san inc crack)", prelaunch: "blister.ball" },
  "Blitzkrieg": { disk: "blitzkrieg 4k file PRODOS (san inc pack)", prelaunch: "blitzkrieg" },
  "BlockChain": { disk: "BLOCKCHAIN (4cade compatible)", prelaunch: "standard" },
  "Bloodsuckers": { disk: "bloodsuckers 14k file PRODOS (san inc pack)", prelaunch: "bloodsuckers" },
  "Boa": { disk: "boa 13k file PRODOS (san inc crack)", prelaunch: "boa" },
  "Bolo": { disk: "bolo 13k file PRODOS (san inc pack)", prelaunch: "bolo" },
  "Bongo's Bash": { disk: "bongo's bash 4k file PRODOS (san inc pack)", prelaunch: "bongos.bash" },
  "Bootskell": { disk: "bootskell 7k file PRODOS (san inc pack)", prelaunch: "bootskell" },
  "Borg": { disk: "borg PRODOS (san inc crack)", prelaunch: "borg" },
  "Boulder Dash": { disk: "boulder dash 12k file PRODOS (san inc pack)", prelaunch: "boulder.dash" },
  "Boulder Dash II": { disk: "boulder dash ii 13k file PRODOS (san inc pack)", prelaunch: "boulder.dash.ii" },
  "Bouncing Kamungas": { disk: "bouncing kamungas PRODOS (san inc pack)", prelaunch: "bouncing.kmngas" },
  "Brainteaser Boulevard": { disk: "brainteaserblvd 11k file PRODOS (san inc pack)", prelaunch: "brainteaserblvd" },
  "Bruce Lee": { disk: "bruce lee PRODOS (san inc crack)", prelaunch: "bruce.lee" },
  "Bubble Bobble": { disk: "bubble bobble PRODOS (san inc pack)", prelaunch: "bubble.bobble" },
  "Bubble Head": { disk: "bubble head PRODOS (san inc pack)", prelaunch: "bubble.head" },
  "Buck Rogers: Planet of Zoom": { disk: "buck rogers PRODOS (san inc crack)", prelaunch: "buck.rogers" },
  "Bug Attack": { disk: "bug attack 12k file PRODOS (san inc crack)", prelaunch: "bug.attack" },
  "Bug Battle": { disk: "bug battle 12k file PRODOS (san inc crack)", prelaunch: "bug.battle" },
  "BurgerTime": { disk: "burgertime 21k file PRODOS (san inc pack)", prelaunch: "burgertime" },
  "ButcherBob '86": { disk: "butcherbob '86 13k file PRODOS (san inc pack)", prelaunch: "butcherbob.86" },
  "Buzzard Bait": { disk: "buzzard bait 15k file PRODOS (san inc crack)", prelaunch: "buzzard.bait" },
  "C'est La Vie": { disk: "c'est la vie 16k file PRODOS (san inc pack)", prelaunch: "cest.la.vie" },
  "Cacorm": { disk: "cacorm 6k file PRODOS (san inc pack)", prelaunch: "cacorm" },
  "California Raisins": { disk: "california raisins PRODOS (san inc pack)", prelaunch: "cali.raisins" },
  "Cannonball Blitz": { disk: "cannonball blitz 16k file PRODOS (san inc crack)", prelaunch: "cannonball.bltz" },
  "Canyon Climber": { disk: "canyon climber 6k file PRODOS (san inc pack)", prelaunch: "canyon.climber" },
  "Captain Goodnight": { disk: "captain goodnight PRODOS (san inc crack)", prelaunch: "captn.goodnight" },
  "Captain Power": { disk: "captain power PRODOS (san inc pack)", prelaunch: "captain.power" },
  "Castle Smurfenstein": { disk: "castle smurfenstein PRODOS (san inc pack)", prelaunch: "smurfen" },
  "Castle Wolfenstein": { disk: "castle wolfenstein 1984 PRODOS (san inc pack)", prelaunch: "wolfen84" },
  "Catacombs": { disk: "catacombs 6502 PRODOS (san inc pack)", prelaunch: "catacombs" },
  "Catacombs 2: Sylvan Idyll": { disk: "sylvan idyll 6502 PRODOS (san inc pack)", prelaunch: "sylvan.idyll" },
  "Catacombs 3: Ether Quest": { disk: "ether quest 6502 PRODOS (san inc pack)", prelaunch: "ether.quest" },
  "Catacombs 4: Sand Trap": { disk: "sand trap PRODOS (san inc pack)", prelaunch: "sand.trap" },
  "Cavern Creatures": { disk: "cavern creatures PRODOS (san inc pack)", prelaunch: "cavrn.creatures" },
  "Caverns of Callisto": { disk: "caverns of calllisto PRODOS (san inc crack)", prelaunch: "cavrns.callisto" },
  "Cavit": { disk: "cavit 8k file PRODOS (san inc pack)", prelaunch: "cavit" },
  "Ceiling Zero": { disk: "ceiling zero 6k file PRODOS (san inc crack)", prelaunch: "ceiling.zero" },
  "Centipede": { disk: "centipede 6k file PRODOS (san inc crack)", prelaunch: "centipede" },
  "Championship Lode Runner": { disk: "championship lode runner PRODOS (san inc pack)(4cade compatible)", prelaunch: "championship.lode.runner" },
  "Chip Out": { disk: "chip out 2k file PRODOS (san inc crack)", prelaunch: "chip.out" },
  "Chivalry": { disk: "chivalry PRODOS (san inc pack)", prelaunch: "standard" },
  "Choplifter": { disk: "choplifter 17k file PRODOS (san inc crack)", prelaunch: "choplifter" },
  "Chrono Warrior": { disk: "chrono warrior PRODOS (san inc pack)", prelaunch: "chrono.warrior" },
  "Clam Bake": { disk: "clam bake 6k file PRODOS (san inc pack)", prelaunch: "clam.bake" },
  "Collect": { disk: "collect 3k file PRODOS (san inc pack)", prelaunch: "collect" },
  "Colorix": { disk: "colorix 3k file PRODOS (san inc pack)", prelaunch: "colorix" },
  "Columns": { disk: "Columns PRODOS (san inc pack)", prelaunch: "standard" },
  "Commando": { disk: "commando PRODOS (san inc pack)", prelaunch: "commando" },
  "Conan": { disk: "conan 1-side bugfix PRODOS (san inc pack)", prelaunch: "conan" },
  "Congo": { disk: "congo 13k file PRODOS (san inc pack)", prelaunch: "congo" },
  "Congo Bongo": { disk: "congo bongo PRODOS (san inc pack)", prelaunch: "congo.bongo" },
  "Conquering Worlds": { disk: "conquering worlds PRODOS (san inc pack)", prelaunch: "conquering.worlds" },
  "Copts and Robbers": { disk: "copts and robbers PRODOS (san inc crack)", prelaunch: "copts.robbers" },
  "Cosmic Combat": { disk: "cosmic combat 13k file PRODOS (san inc pack)", prelaunch: "cosmic.combat" },
  "County Fair": { disk: "county fair 12k file PRODOS (san inc pack)", prelaunch: "county.fair" },
  "Cracky": { disk: "cracky 5k file PRODOS (san inc pack)", prelaunch: "cracky" },
  "Crazy Mazey": { disk: "crazy mazey PRODOS (san inc crack)", prelaunch: "crazy.mazey" },
  "Creepy Corridors": { disk: "creepy corridors 12k file PRODOS (san inc pack)", prelaunch: "creepy.corridors" },
  "Cricketeer": { disk: "cricketeer 16k file PRODOS (san inc pack)", prelaunch: "cricketeer" },
  "Crime Wave": { disk: "crime wave PRODOS (san inc pack)", prelaunch: "crime.wave" },
  "Crisis Mountain": { disk: "crisis mountain PRODOS (san inc crack)", prelaunch: "crisis.mountain" },
  "Cross City": { disk: "cross city PRODOS (san inc pack)", prelaunch: "cross.city" },
  "Crossbow": { disk: "crossbow PRODOS (san inc pack)", prelaunch: "crossbow" },
  "Crossfire": { disk: "crossfire 8k file PRODOS (san inc pack)", prelaunch: "crossfire" },
  "Crystal Castles": { disk: "crystal castles 11k file PRODOS (san inc pack)", prelaunch: "crystal.castles" },
  "Cubit": { disk: "cubit 9k file PRODOS (san inc pack)", prelaunch: "cubit" },
  "Cyber Strike": { disk: "cyber.strike 12k file PRODOS (san inc crack)", prelaunch: "cyber.strike" },
  "Cyclod": { disk: "cyclod 13k file PRODOS (san inc pack)", prelaunch: "cyclod" },
  "Cyclotron": { disk: "cyclotron 10k file PRODOS (san inc pack)", prelaunch: "cyclotron" },
  "D-Generation": { disk: "d-generation PRODOS (san inc crack)", prelaunch: "d.generation" },
  "Dangerous Dave": { disk: "dangerous dave PRODOS (san inc pack)", prelaunch: "dangerous.dave" },
  "Darkstar Unhinged": { disk: "darkstar unhinged PRODOS (san inc pack)", prelaunch: "darkstar.unhngd" },
  "David's Midnight Magic": { disk: "david's midnight magic PRODOS (san inc crack)", prelaunch: "davids.magic" },
  "Dawn Treader": { disk: "dawn treader 18k file PRODOS (san inc pack)", prelaunch: "dawn.treader" },
  "Death Sword": { disk: "deathsword PRODOS (san inc pack)", prelaunch: "death.sword" },
  "Deathbounce": { disk: "deathbounce 5k file PRODOS (san inc pack)", prelaunch: "deathbounce" },
  "Deep Space": { disk: "deep space PRODOS (san inc pack)", prelaunch: "deep.space" },
  "Defender": { disk: "defender 9k file PRODOS (san inc pack)", prelaunch: "defender" },
  "Demonic Decks": { disk: "demonic decks PRODOS (san inc pack)", prelaunch: "demonic.decks" },
  "Diamond Mine": { disk: "diamond mine 17k file PRODOS (san inc crack)", prelaunch: "diamond.mine" },
  "Dig 'Em": { disk: "dig 'em 8k file PRODOS (san inc crack)", prelaunch: "dig.em" },
  "Dig Dug": { disk: "dig dug 12k file PRODOS (san inc pack)", prelaunch: "dig.dug" },
  "Dino Eggs": { disk: "dino eggs PRODOS (san inc pack)", prelaunch: "dino.eggs" },
  "Dino Smurf": { disk: "dino smurf PRODOS (san incn pack)", prelaunch: "dino.smurf" },
  "Dogfight II": { disk: "dogfight ii 17k file PRODOS (san inc crack)", prelaunch: "dogfight.ii" },
  "Donkey Kong": { disk: "donkey kong PRODOS (san inc pack)", prelaunch: "donkey.kong" },
  "Double Trouble": { disk: "double trouble PRODOS (san inc pack)", prelaunch: "standard" },
  "Dragonfire": { disk: "dragonfire 15k file PRODOS (san inc crack)", prelaunch: "dragonfire" },
  "Drelbs": { disk: "drelbs 16k file PRODOS (san inc crack)", prelaunch: "drelbs" },
  "Drol": { disk: "drol PRODOS (san inc crack)", prelaunch: "drol" },
  "Dung Beetles": { disk: "dung beetles 10k file PRODOS (san inc crack)", prelaunch: "dung.beetles" },
  "Early Bird": { disk: "early bird 8k file PRODOS (san inc pack)", prelaunch: "early.bird" },
  "Eggs-It": { disk: "eggs it 20k file PRODOS (san inc crack)", prelaunch: "eggs.it" },
  "Electroarena": { disk: "electroarena PRODOS (san inc pack)", prelaunch: "electroarena" },
  "Epoch": { disk: "epoch 16k file PRODOS (san inc pack)", prelaunch: "epoch" },
  "Escape!": { disk: "escape 10k file PRODOS (san inc crack)", prelaunch: "escape" },
  "Evolution": { disk: "evolution PRODOS (san inc crack)", prelaunch: "evolution" },
  "Exterminator": { disk: "exterminator 16k file PRODOS (san inc pack)", prelaunch: "exterminator" },
  "Falcons": { disk: "falcons 14k file PRODOS (san inc pack)", prelaunch: "falcons" },
  "Fat City": { disk: "fat city PRODOS (san inc pack)", prelaunch: "fat.city" },
  "Federation": { disk: "federation 7k file PRODOS (san inc pack)", prelaunch: "federation" },
  "Fido": { disk: "fido 17k file PRODOS (san inc pack)", prelaunch: "fido" },
  "Fire and Ice": { disk: "fire and ice 12k file PRODOS (san inc pack)", prelaunch: "fire.and.ice" },
  "Firebird": { disk: "firebird 11k file PRODOS (san inc pack)", prelaunch: "firebird" },
  "Firebug": { disk: "firebug 8k file PRODOS (san inc crack)", prelaunch: "firebug" },
  "Flak": { disk: "flak 17k file PRODOS (san inc pack)", prelaunch: "flak" },
  "Flapple Bird": { disk: "flapple bird 4k file PRODOS (san inc pack)", prelaunch: "flapple.bird" },
  "Flip Out": { disk: "flip out 9k file PRODOS (san inc pack)", prelaunch: "standard" },
  "Flobynoid": { disk: "flobynoid PRODOS (san inc pack)", prelaunch: "flobynoid" },
  "Floppy": { disk: "floppy PRODOS (san inc pack)", prelaunch: "floppy" },
  "Fly Wars": { disk: "fly wars PRODOS (san inc pack)", prelaunch: "fly.wars" },
  "Force 7": { disk: "force 7 27k file PRODOS (san inc crack)", prelaunch: "force.7" },
  "Frazzle": { disk: "frazzle 9k file PRODOS (san inc pack)", prelaunch: "frazzle" },
  "Free Fall": { disk: "free fall 15k file PRODOS (san inc pack)", prelaunch: "free.fall" },
  "Frogger": { disk: "frogger 15k file PRODOS (san inc pack)", prelaunch: "frogger" },
  "Frogger II": { disk: "frogger ii PRODOS (san inc pack)", prelaunch: "frogger.ii" },
  "Froggo": { disk: "froggo 27k file PRODOS (san inc pack)", prelaunch: "froggo" },
  "G I Joe": { disk: "g.i. joe PRODOS (san inc pack)", prelaunch: "g.i.joe" },
  "Galactic Attack": { disk: "galactic attack PRODOS (san inc pack)", prelaunch: "galactic.attack" },
  "Galaxian": { disk: "galaxian 10k file PRODOS (san inc pack)", prelaunch: "galaxian" },
  "Galaxy Gates": { disk: "galaxy gates 8k file PRODOS (san inc pack)", prelaunch: "galaxy.gates" },
  "Game Boy Tetris": { disk: "game boy tetris 16k file PRODOS (san inc pack)", prelaunch: "gb.tetris" },
  "Gamma Goblins": { disk: "gamma goblins 14k file PRODOS (san inc crack)", prelaunch: "gamma.goblins" },
  "Gauntlet": { disk: "gauntlet PRODOS (san inc crack)", prelaunch: "gauntlet" },
  "Gemini": { disk: "gemini 7k file PRODOS (san inc pack)", prelaunch: "gemini" },
  "Genesis": { disk: "genesis 13k file PRODOS (san inc pack)", prelaunch: "genesis" },
  "Genetic Drift": { disk: "genetic drift 13k file PRODOS (san inc crack)", prelaunch: "genetic.drift" },
  "Genius": { disk: "genius PRODOS (san inc pack)", prelaunch: "genius" },
  "Genius 2": { disk: "genius 2 PRODOS (san inc pack)", prelaunch: "genius.2" },
  "Genius 3": { disk: "genius 3 PRODOS (san inc pack)", prelaunch: "genius.3" },
  "Ghostbusters": { disk: "ghostbusters PRODOS (san inc pack)", prelaunch: "ghostbusters" },
  "Glider": { disk: "glider (san inc pack)(4cade compatible)", prelaunch: "glider" },
  "Glutton": { disk: "glutton 12k file PRODOS (san inc crack)", prelaunch: "glutton" },
  "Gold Rush": { disk: "gold rush 12k file PRODOS (san inc pack)", prelaunch: "gold.rush" },
  "Gorgon": { disk: "gorgon PRODOS (san inc crack)", prelaunch: "gorgon" },
  "Grapple": { disk: "grapple 16k file PRODOS (san inc pack)", prelaunch: "grapple" },
  "Gremlins": { disk: "gremlins 24k file PRODOS (san inc pack)", prelaunch: "gremlins" },
  "Guardian": { disk: "guardian 8k file PRODOS (san inc crack)", prelaunch: "guardian" },
  "Gumball": { disk: "gumball PRODOS (san inc pack)", prelaunch: "gumball" },
  "Guntus": { disk: "guntus 8k file PRODOS (san inc pack)", prelaunch: "guntus" },
  "H E R O": { disk: "hero 12k file PRODOS (san inc pack) (fixes refresh bug in original game)", prelaunch: "h.e.r.o" },
  "Hadron": { disk: "hadron 21k file PRODOS (san inc crack)", prelaunch: "hadron" },
  "Handy Dandy": { disk: "handy dandy 9k file PRODOS (san inc pack)", prelaunch: "handy.dandy" },
  "Hard Hat Mack": { disk: "hard hat mack 19k file PRODOS (san inc crack)", prelaunch: "hard.hat.mack" },
  "Head On": { disk: "head on 6k file PRODOS (san inc crack)", prelaunch: "head.on" },
  "Heavy Barrel": { disk: "heavy barrel PRODOS (san inc pack)", prelaunch: "heavy.barrel" },
  "Helicopter Rescue": { disk: "helicopter rescue 25k file PRODOS (san inc crack)", prelaunch: "heli.rescue" },
  "Hell Storm": { disk: "hellstorm 11k file PRODOS (san inc pack)", prelaunch: "hellstorm" },
  "High Rise": { disk: "high rise 9k file PRODOS (san inc pack)", prelaunch: "high.rise" },
  "Hopman": { disk: "hopman (4am pack)", prelaunch: "hopman" },
  "Horizon V": { disk: "horizon v 20k file PRODOS (san inc crack)", prelaunch: "horizon.v" },
  "Hungryboy": { disk: "hungryboy 10k file PRODOS (san inc pack)", prelaunch: "hungryboy" },
  "Hyper Head On": { disk: "hyper head on 7k file PRODOS (san inc crack)", prelaunch: "hyper.head.on" },
  "I.O. Silver": { disk: "i.o. silver PRODOS (san inc pack)", prelaunch: "i.o.silver" },
  "Ikari Warriors": { disk: "ikari warriors PRODOS (san inc pack)", prelaunch: "ikari.warriors" },
  "Impetus": { disk: "impetus 10k file PRODOS (san inc pack)", prelaunch: "impetus" },
  "Impossible Mission": { disk: "impossible mission PRODOS (san inc pack)", prelaunch: "impossible.miss" },
  "Impossible Mission II": { disk: "impossible mission ii PRODOS (san inc pack)", prelaunch: "impossible.mi2" },
  "Indiana Jones": { disk: "Indiana Jones", prelaunch: "indiana.jones" },
  "Infiltrator": { disk: "infiltrator PRODOS (san inc pack)", prelaunch: "infiltrator" },
  "Infiltrator 2": { disk: "infiltrator 2 PRODOS (san inc pack)", prelaunch: "infiltrator.2" },
  "Into the Eagle's Nest": { disk: "into the eagle's nest PRODOS (san inc pack)", prelaunch: "eagles.nest" },
  "Invasion Force": { disk: "invasion force 3k file PRODOS (san inc pack)", prelaunch: "invasion.force" },
  "It's the Pits": { disk: "its the pits PRODOS (san inc pack)", prelaunch: "its.the.pits" },
  "J-Bird": { disk: "j-bird 21k file PRODOS (san inc crack)", prelaunch: "j.bird" },
  "Jawbreaker": { disk: "jawbreaker 8k file PRODOS (san inc crack)", prelaunch: "jawbreaker" },
  "Jawbreaker II": { disk: "jawbreaker ii PRODOS (san inc crack)", prelaunch: "jawbreaker.ii" },
  "Jellyfish": { disk: "jellyfish 17k file PRODOS (san inc pack)", prelaunch: "jellyfish" },
  "Joust": { disk: "joust 26k file PRODOS (san inc pack)", prelaunch: "joust" },
  "Jouster": { disk: "jouster 7k file PRODOS (san inc pack)", prelaunch: "jouster" },
  "Juggler": { disk: "juggler 15k file PRODOS (san inc crack)", prelaunch: "juggler" },
  "Jump Jet": { disk: "jump jet 14k file PRODOS (san inc crack)", prelaunch: "jump.jet" },
  "Jumpman": { disk: "jumpman PRODOS (san inc pack)", prelaunch: "jumpman" },
  "Jungle Hunt": { disk: "jungle hunt PRODOS (san inc crack)", prelaunch: "jungle.hunt" },
  "Kaboom!": { disk: "kaboom 7k file PRODOS (san inc pack)", prelaunch: "kaboom" },
  "Kamikaze": { disk: "kamikaze 8k file PRODOS (san inc pack)", prelaunch: "kamikaze" },
  "Karateka": { disk: "karateka PRODOS (san inc pack)", prelaunch: "karateka" },
  "Kid Niki": { disk: "kid niki PRODOS (san inc pack)", prelaunch: "kid.niki" },
  "Kung Fu Master": { disk: "kung fu master PRODOS (san inc pack)", prelaunch: "kung.fu.master" },
  "Labyrinth": { disk: "labyrinth 19k file PRODOS (san inc pack)", prelaunch: "standard" },
  "Lady Tut": { disk: "lady tut 6502 PRODOS (san inc pack)", prelaunch: "lady.tut" },
  "Lamb Chops!": { disk: "lamb chops 5k file PRODOS (san inc pack)", prelaunch: "lamb.chops" },
  "Lancaster": { disk: "lancaster PRODOS (san inc crack)", prelaunch: "lancaster" },
  "Laser Bounce": { disk: "laser bounce 9k file PRODOS (san inc pack)", prelaunch: "standard" },
  "Lazer Silk": { disk: "lazer silk 12k file PRODOS (san inc crack)", prelaunch: "lazer.silk" },
  "Lemmings": { disk: "lemmings PRODOS (san inc pack)", prelaunch: "lemmings" },
  "Lemmings (Sirius)": { disk: "lemmings (sirius) PRODOS (san inc pack)", prelaunch: "lemm.sir" },
  "Lethal Labyrinth": { disk: "lethal labyrinth PRODOS (san inc pack)", prelaunch: "lethal.labyrnth" },
  "Lift": { disk: "lift 6k file PRODOS (san inc pack)", prelaunch: "lift" },
  "Little Brick Out": { disk: "little brick out 4k file PRODOS (san inc pack)", prelaunch: "little.brk.out" },
  "Little Computer People": { disk: "little computer people PRODOS (san inc pack)", prelaunch: "little.comp.ppl" },
  "Lock 'n' Chase": { disk: "lock 'n' chase 15k file PRODOS (san inc pack)", prelaunch: "lock.n.chase" },
  "Lode Runner": { disk: "lode runner PRODOS (san inc pack)", prelaunch: "lode.runner" },
  "Lost Tomb": { disk: "lost tomb 18k file PRODOS (san inc crack)", prelaunch: "lost.tomb" },
  "Lunar Explorer": { disk: "lunar explorer 13k file PRODOS (san inc pack)", prelaunch: "lunar.explorer" },
  "Lunar Leepers": { disk: "lunar leepers PRODOS (san inc crack)", prelaunch: "lunar.leepers" },
  "M I R V": { disk: "mirv 6k file PRODOS (san inc pack)", prelaunch: "m.i.r.v" },
  "Mad Bomber": { disk: "mad bomber 3k file PRODOS (san inc crack)", prelaunch: "standard" },
  "Mad Rat": { disk: "mad rat 14k file PRODOS (san inc pack)", prelaunch: "mad.rat" },
  "Manic Miner": { disk: "manic miner 16k file PRODOS (san inc pack)", prelaunch: "manic.miner" },
  "Mapple": { disk: "mapple 10k file PRODOS (san inc pack)", prelaunch: "mapple" },
  "Marauder": { disk: "marauder PRODOS (san inc pack)", prelaunch: "marauder" },
  "Marble Madness": { disk: "marble madness PRODOS (san inc pack)", prelaunch: "marble.madness" },
  "Mario Bros.": { disk: "mario bros 14k file PRODOS (san inc pack)", prelaunch: "mario.bros" },
  "Mars Cars": { disk: "mars cars 19k file PRODOS (san inc pack)", prelaunch: "mars.cars" },
  "Mating Zone": { disk: "mating zone PRODOS (san inc crack)", prelaunch: "mating.zone" },
  "Maxwell Manor": { disk: "maxwell manor 32k file PRODOS (san inc pack)", prelaunch: "maxwell.manor" },
  "Mazeblox": { disk: "mazeblox PRODOS (san inc pack)", prelaunch: "mazeblox" },
  "Mazy": { disk: "mazy 5k file PRODOS (san inc pack)", prelaunch: "mazy" },
  "Mazy2": { disk: "mazy2 7k file PRODOS (san inc pack)", prelaunch: "mazy2" },
  "Megabots": { disk: "megabots PRODOS (san inc pack)", prelaunch: "megabots" },
  "Micro Invaders": { disk: "micro invaders 4k file PRODOS (san inc pack)", prelaunch: "micro.invaders" },
  "Microwave": { disk: "microwave PRODOS (san inc pack)", prelaunch: "microwave" },
  "Mieyen": { disk: "mieyen PRODOS (4am pack)", prelaunch: "mieyen" },
  "Millennium Leaper": { disk: "millenium leaper 10k file PRODOS (san inc pack)", prelaunch: "millnm.leaper" },
  "Mine Sweep": { disk: "mine sweep 5k file PRODOS (san inc pack)", prelaunch: "mine.sweep" },
  "Miner 2049er": { disk: "miner 2049er PRODOS (san inc pack)", prelaunch: "miner.2049er" },
  "Miner II": { disk: "miner ii PRODOS (san inc crack)", prelaunch: "miner.ii" },
  "Ming's Challenge": { disk: "ming's challenge PRODOS (san inc crack)", prelaunch: "mings.challenge" },
  "Minit Man": { disk: "minit man PRODOS (san inc pack)", prelaunch: "minit.man" },
  "Minotaur": { disk: "minotaur PRODOS (san inc pack)", prelaunch: "minotaur" },
  "Mission on Thunderhead": { disk: "mission on thunderhead PRODOS (san inc pack)", prelaunch: "thunderhead" },
  "Monster Mash": { disk: "monster mash PRODOS (san inc pack)", prelaunch: "monster.mash" },
  "Montezuma's Revenge": { disk: "montezuma's revenge 22k file PRODOS (san inc crack)", prelaunch: "montezuma" },
  "Moon Patrol": { disk: "moon patrol 18k file PRODOS (san inc crack)", prelaunch: "moon.patrol" },
  "Mouskattack": { disk: "mouskattack 12k file PRODOS (san inc crack)", prelaunch: "mouskattack" },
  "Mr. Cool": { disk: "mr.cool 11k file PRODOS (san inc crack)", prelaunch: "mr.cool" },
  "Mr. Robot": { disk: "mr. robot 22k file PRODOS (san inc pack)", prelaunch: "mr.robot" },
  "Ms. Pacman": { disk: "ms. pacman 12k file PRODOS (san inc pack)", prelaunch: "ms.pacman" },
  "Mutant": { disk: "mutant 15k file PRODOS (san inc pack)", prelaunch: "mutant" },
  "Mutant (Steve Waldo)": { disk: "mutant (steve waldo) 21k file PRODOS (san inc pack)", prelaunch: "mutant.sw" },
  "N O R A D": { disk: "norad 7k file PRODOS (san inc pack)", prelaunch: "norad" },
  "Narnia": { disk: "narnia 18k file PRODOS (san inc pack)", prelaunch: "narnia" },
  "Neon": { disk: "neon PRODOS (san inc pack)", prelaunch: "neon" },
  "Neptune": { disk: "neptune 16k file PRODOS (san inc pack)", prelaunch: "neptune" },
  "Neuras": { disk: "neuras 6k file PRODOS (san inc pack)", prelaunch: "neuras" },
  "Neut Tower": { disk: "neut tower 17k file PRODOS (san inc pack)", prelaunch: "neut.tower" },
  "Neutrons": { disk: "neutrons 8k file PRODOS (san inc pack)", prelaunch: "standard" },
  "Nibbler": { disk: "nibbler 9k file PRODOS (san inc crack)", prelaunch: "nibbler" },
  "Nibbler (B. Iverson)": { disk: "nibbler (brent iverson) 3k file PRODOS (san inc pack)", prelaunch: "nibbler.brent.iverson" },
  "Night Crawler": { disk: "night crawler 6k file PRODOS (san inc pack)", prelaunch: "night.crawler" },
  "Night Falls": { disk: "night falls PRODOS (san inc pack)", prelaunch: "night.falls" },
  "Night Mission Pinball": { disk: "night mission 18k file PRODOS (san inc crack)", prelaunch: "night.mission" },
  "Night Stalker": { disk: "night stalker 21k file PRODOS (san inc crack)", prelaunch: "night.stalker" },
  "Nightmare Gallery": { disk: "nightmare gallery 12k file PRODOS (san inc pack)", prelaunch: "nightmare" },
  "O'Riley's Mine": { disk: "orileys mine 11k file PRODOS (san inc crack)", prelaunch: "orileys.mine" },
  "Oid Zone": { disk: "oid zone 19k file PRODOS (san inc pack)", prelaunch: "oid.zone" },
  "Oil's Well": { disk: "oil's well PRODOS (san inc pack)", prelaunch: "oils.well" },
  "Orbitron": { disk: "orbitron 12k file PRODOS (san inc crack)", prelaunch: "orbitron" },
  "Osotos": { disk: "osotos 8k file PRODOS (san inc pack)", prelaunch: "osotos" },
  "Outpost": { disk: "outpost 11k file PRODOS (san inc pack)", prelaunch: "outpost" },
  "Outworld": { disk: "Outworld", prelaunch: "outworld" },
  "Pacman": { disk: "pacman (Atari) 14k file PRODOS (san inc pack)", prelaunch: "pacman" },
  "Paipec": { disk: "paipec 7k file PRODOS (san inc pack)", prelaunch: "paipec" },
  "Pandora's Box": { disk: "pandora's box 14k file PRODOS (san inc pack)", prelaunch: "pandoras.box" },
  "Panic Button!": { disk: "panic button PRODOS (san inc pack)", prelaunch: "panic.button" },
  "Paperboy": { disk: "paperboy PRODOS (san inc pack)", prelaunch: "paperboy" },
  "Peeping Tom": { disk: "peeping tom PRODOS (san inc crack)", prelaunch: "peeping.tom" },
  "Pegasus II": { disk: "pegasus ii PRODOS (san inc pack)", prelaunch: "pegasus.ii" },
  "Penetrator": { disk: "penetrator 14k file PRODOS (san inc pack)", prelaunch: "penetrator" },
  "Pengo": { disk: "pengo PRODOS (san inc pack)", prelaunch: "pengo" },
  "Pentapus": { disk: "pentapus 22k file PRODOS (san inc pack)", prelaunch: "pentapus" },
  "People Pong": { disk: "people pong 12k file PRODOS (san inc pack)", prelaunch: "people.pong" },
  "Pest Patrol": { disk: "pest patrol 17k file PRODOS (san inc pack)", prelaunch: "pest.patrol" },
  "Phantoms Five": { disk: "phantoms five 26k file PRODOS (san inc crack)", prelaunch: "phantoms.five" },
  "Pharaoh's Revenge": { disk: "pharaoh's revenge PRODOS (san inc pack)", prelaunch: "pharaohs.revng" },
  "Phaser Fire": { disk: "phaser fire 12k file PRODOS (san inc crack)", prelaunch: "phaser.fire" },
  "Photar": { disk: "photar 8k file PRODOS (san inc pack)", prelaunch: "photar" },
  "Picnic Paranoia": { disk: "picnic paranoia 15k file PRODOS (san inc pack)", prelaunch: "picnic.paranoia" },
  "Pie-Man": { disk: "pie-man 10k file PRODOS (san inc pack)", prelaunch: "pieman" },
  "Pig Pen": { disk: "pig pen 12k file PRODOS (san inc pack)", prelaunch: "pig.pen" },
  "Pill Box": { disk: "pill box 11k file PRODOS (san inc pack)", prelaunch: "pill.box" },
  "Pipe Dream": { disk: "Pipe Dream (4am crack)(4cade compatible)", prelaunch: "pipe.dream" },
  "Pitfall II": { disk: "pitfall II 14k file PRODOS (san inc crack)", prelaunch: "pitfall.ii" },
  "Planet Protector": { disk: "planet protector 7k file PRODOS (san inc pack)", prelaunch: "planet.protectr" },
  "Planetoids": { disk: "planetoids 3k file PRODOS (san inc crack)", prelaunch: "planetoids" },
  "Plasmania": { disk: "plasmania 21k file PRODOS (san inc crack)", prelaunch: "plasmania" },
  "Platoon": { disk: "platoon PRODOS (san inc pack)", prelaunch: "platoon" },
  "Pollywog": { disk: "pollywog 21k file PRODOS (san inc pack)", prelaunch: "pollywog" },
  "Pooyan": { disk: "pooyan 15k file PRODOS (san inc crack)", prelaunch: "pooyan" },
  "Prince of Persia": { disk: "prince of persia PRODOS (san inc crack)", prelaunch: "prince.of.persia" },
  "Pulsar II": { disk: "pulsar ii 15k file PRODOS (san inc crack)", prelaunch: "pulsar.ii" },
  "Puyo Puyo": { disk: "puyo puyo no sound 6502 8k file (san inc pack)", prelaunch: "puyo.puyo" },
  "Qix": { disk: "qix PRODOS (san inc crack)", prelaunch: "qix" },
  "Quadrant 6112": { disk: "quadrant 6112 PRODOS (san inc crack)", prelaunch: "quadrant.6112" },
  "Quasar": { disk: "quasar 14k file PRODOS (san inc pack)", prelaunch: "quasar" },
  "Radwarrior": { disk: "radwarrior PRODOS (san inc pack)", prelaunch: "radwarrior" },
  "Raid Over Moscow": { disk: "raid over moscow PRODOS (san inc crack)", prelaunch: "raid.ovr.moscow" },
  "Raiders of the Lost Ring": { disk: "raiders of the lost ring 9k file PRODOS (san inc pack)", prelaunch: "raiders.of.ring" },
  "Rainbow Zone": { disk: "rainbow zone 10k file PRODOS (san inc pack)", prelaunch: "rainbow.zone" },
  "Rampage": { disk: "rampage PRODOS (san inc pack)", prelaunch: "rampage" },
  "Randamn": { disk: "randamn PRODOS (san inc crack)", prelaunch: "randamn" },
  "Raster Blaster": { disk: "raster blaster 13k file PRODOS (san inc crack)", prelaunch: "raster.blaster" },
  "Realm of Impossibility": { disk: "realm of impossibility PRODOS (san inc pack)", prelaunch: "realm.imposs" },
  "Rear Guard": { disk: "rear guard PRODOS (san inc crack)", prelaunch: "rear.guard" },
  "Red Alert": { disk: "red alert 10k file PRODOS (san inc crack)", prelaunch: "standard" },
  "Renegade": { disk: "Renegade (4am crack)", prelaunch: "renegade" },
  "Repton": { disk: "repton PRODOS (san inc pack)", prelaunch: "repton" },
  "Rescue Raiders": { disk: "rescue raiders PRODOS (san inc pack)", prelaunch: "rescue.raiders" },
  "Retro Fever": { disk: "retro fever 14k file PRODOS (san inc pack)", prelaunch: "retro.fever" },
  "Ribbit": { disk: "ribbit 9k file PRODOS (san inc pack)", prelaunch: "ribbit" },
  "Roach Hotel": { disk: "roach hotel 18k file PRODOS (san inc crack)", prelaunch: "roach.hotel" },
  "Roadblock": { disk: "roadblock 10k file PRODOS (san inc crack)", prelaunch: "roadblock" },
  "Robocop": { disk: "robocop PRODOS (san inc pack)", prelaunch: "robocop" },
  "Robot Battle": { disk: "robot battle 8k file PRODOS (san inc pack)", prelaunch: "robot.battle" },
  "Robotics": { disk: "robotics 20k file PRODOS (san inc pack)", prelaunch: "robotics" },
  "Robotron 2084": { disk: "robotron 2084 13k file PRODOS (san inc pack)", prelaunch: "robotron.2084" },
  "Round About": { disk: "round about PRODOS (san inc pack)", prelaunch: "round.about" },
  "Run For It": { disk: "run for it PRODOS (san inc pack)", prelaunch: "run.for.it" },
  "Run For The Money": { disk: "run for the money PRODOS (san inc pack)", prelaunch: "run.for.money" },
  "Ruptus": { disk: "ruptus 8k file PRODOS (san inc pack)", prelaunch: "ruptus" },
  "Russki Duck": { disk: "russki duck 15k file PRODOS (san inc crack)", prelaunch: "russki.duck" },
  "Sabotage": { disk: "sabotage 11k file PRODOS (san inc pack)", prelaunch: "sabotage" },
  "Sabotage II": { disk: "sabotage ii 8k file PRODOS (san inc pack)", prelaunch: "sabotage.ii" },
  "Sadar's Revenge": { disk: "sadar's revenge 13k file PRODOS (san inc pack)", prelaunch: "sadars.revenge" },
  "Sammy Lightfoot": { disk: "sammy lightfoot PRODOS (san inc pack)", prelaunch: "sammy.lightfoot" },
  "Sanitron": { disk: "sanitron 13k file PRODOS (san inc pack)", prelaunch: "sanitron" },
  "Saracen": { disk: "saracen PRODOS (san inc crack)", prelaunch: "saracen" },
  "Sea Dragon": { disk: "sea dragon PRODOS (san inc pack)", prelaunch: "standard" },
  "Seafox": { disk: "seafox 19k file PRODOS (san inc pack)", prelaunch: "seafox" },
  "Serpentine": { disk: "serpentine 18k file PRODOS (san inc crack)", prelaunch: "serpentine" },
  "Shamus": { disk: "shamus 11k file PRODOS (san inc crack)", prelaunch: "shamus" },
  "Shatterstar": { disk: "shatterstar PRODOS (san inc pack)", prelaunch: "shatterstar" },
  "Sheila": { disk: "sheila PRODOS (san inc pack)", prelaunch: "sheila" },
  "Shooting Gallery": { disk: "shooting gallery 3k file PRODOS (san inc pack)", prelaunch: "shooting.gallry" },
  "Short Circuit": { disk: "short circuit PRODOS (san inc pack)", prelaunch: "short.circuit" },
  "Shufflepuck Cafe": { disk: "shufflepuck cafe (san inc pack)(4cade compatible)", prelaunch: "shflpuck" },
  "Shuttle Intercept": { disk: "shuttle intercept 5k file PRODOS (san inc pack)", prelaunch: "shuttle.intercept" },
  "Sigma Seven": { disk: "sigma seven 7k file PRODOS (san inc pack)", prelaunch: "sigma.seven" },
  "Situation Critical": { disk: "situation critical PRODOS (san inc crack)", prelaunch: "situation.crtcl" },
  "Skyfox": { disk: "skyfox PRODOS (san inc pack)", prelaunch: "skyfox" },
  "Snack Attack": { disk: "snack attack 15k file PRODOS (san inc crack)", prelaunch: "snack.attack" },
  "Snake Byte": { disk: "snake byte 9k file PRODOS (san inc crack)", prelaunch: "snake.byte" },
  "SnakeBYTE Remix": { disk: "snakebyte remix 8k file PRODOS (san inc pack)", prelaunch: "snakebyte.remix" },
  "Sneakers": { disk: "sneakers 17k file PRODOS (san inc pack)", prelaunch: "sneakers" },
  "Snoggle": { disk: "snoggle 16k file PRODOS (san inc crack)", prelaunch: "snoggle" },
  "Soko-Ban": { disk: "soko-ban PRODOS (san inc pack)", prelaunch: "soko.ban" },
  "Space Eggs": { disk: "space eggs 10k file PRODOS (san inc crack)", prelaunch: "space.eggs" },
  "Space Kadet": { disk: "space kadet 14k file PRODOS (san inc pack)", prelaunch: "space.kadet" },
  "Space Quarks": { disk: "space quarks 11k file PRODOS (san inc crack)", prelaunch: "space.quarks" },
  "Space Race": { disk: "space race 7k file PRODOS (san inc pack)", prelaunch: "space.race" },
  "Space Raiders": { disk: "space raiders 9k file PRODOS (san inc crack) (IIe compatible)", prelaunch: "space.raiders" },
  "Space Rescue": { disk: "space rescue 9k file PRODOS (san inc pack)", prelaunch: "space.rescue" },
  "Space Spikes": { disk: "space spikes PRODOS (san inc pack)", prelaunch: "space.spikes" },
  "Space Warrior": { disk: "space warrior 5k file PRODOS (san inc pack)", prelaunch: "space.warrior" },
  "Spare Change": { disk: "spare change PRODOS (san inc crack)", prelaunch: "spare.change" },
  "Spectre": { disk: "spectre 14k file PRODOS (san inc pack)", prelaunch: "spectre" },
  "Spellwielder": { disk: "spellwielder PRODOS (san inc pack)", prelaunch: "spellwielder" },
  "Spider Raid": { disk: "spider raid 14k file PRODOS (san inc crack)", prelaunch: "spider.raid" },
  "Spiderbot": { disk: "spiderbot PRODOS (san inc pack)", prelaunch: "spiderbot" },
  "Spindizzy": { disk: "spindizzy 25k file PRODOS (san inc pack)", prelaunch: "spindizzy" },
  "Spud and Mug Shot": { disk: "spud and mugshot PRODOS (san inc pack)", prelaunch: "spud.mugshot" },
  "Spy Hunter": { disk: "spy hunter 19k file PRODOS (san inc pack)", prelaunch: "spy.hunter" },
  "Spy vs Spy": { disk: "spy vs spy PRODOS (san inc pack)", prelaunch: "spy.vs.spy" },
  "Spy vs Spy 2": { disk: "spy vs spy 2 PRODOS (san inc crack)", prelaunch: "spy.vs.spy.2" },
  "Spy vs Spy 3": { disk: "spy vs spy 3 PRODOS (san inc crack)", prelaunch: "spy.vs.spy.3" },
  "Spy's Demise": { disk: "spys demise 8k file PRODOS (san inc pack)", prelaunch: "spys.demise" },
  "Star Avenger": { disk: "star avenger 11k file PRODOS (san inc pack)", prelaunch: "star.avenger" },
  "Star Blazer": { disk: "star blazer 19k file PRODOS (san inc crack)", prelaunch: "star.blazer" },
  "Star Clones": { disk: "star clones 16k file PRODOS (san inc pack)", prelaunch: "star.clones" },
  "Star Cruiser": { disk: "star cruiser 8k file PRODOS (san inc crack)", prelaunch: "star.cruiser" },
  "Star Dance": { disk: "star dance 10k file PRODOS (san inc crack)", prelaunch: "star.dance" },
  "Star Maze": { disk: "star maze 16k file PRODOS (san inc pack)", prelaunch: "star.maze" },
  "Star Thief": { disk: "star thief 9k file PRODOS (san inc crack)", prelaunch: "star.thief" },
  "Starball": { disk: "starball PRODOS (san inc pack)", prelaunch: "starball" },
  "Starblaster": { disk: "starblaster 10k file PRODOS (san inc pack)", prelaunch: "starblaster" },
  "Stargate": { disk: "stargate 16k file PRODOS (san inc pack)", prelaunch: "stargate" },
  "Starglider": { disk: "starglider 31k file PRODOS (san inc pack)", prelaunch: "starglider" },
  "Starmines": { disk: "starmines 6k file PRODOS (san inc pack)", prelaunch: "starmines" },
  "Station 5": { disk: "station 5 PRODOS (san inc pack)", prelaunch: "standard" },
  "Stellar 7": { disk: "stellar 7 PRODOS (san inc pack)", prelaunch: "stellar.7" },
  "Succession": { disk: "succession 6k file PRODOS (san inc pack)", prelaunch: "succession" },
  "Suicide!": { disk: "suicide 4k file PRODOS (san inc crack)", prelaunch: "suicide" },
  "Super Bunny": { disk: "super bunny PRODOS (san inc pack)", prelaunch: "super.bunny" },
  "Super Puckman": { disk: "super puckman 15k file PRODOS (san inc pack)", prelaunch: "super.puckman" },
  "Super Taxman 2": { disk: "super taxman 2 PRODOS (san inc crack)", prelaunch: "super.taxman.2" },
  "Super Zaxxon": { disk: "super zaxxon PRODOS (san inc crack)", prelaunch: "super.zaxxon" },
  "Svellas": { disk: "svellas 7k file PRODOS (san inc pack)", prelaunch: "svellas" },
  "Swashbuckler": { disk: "swashbuckler PRODOS (san inc pack)", prelaunch: "swashbuckler" },
  "Sword of Sheol": { disk: "sword of sheol PRODOS (san inc crack)", prelaunch: "sword.of.sheol" },
  "SwordWork": { disk: "swordwork 6k file PRODOS (san inc pack)", prelaunch: "swordwork" },
  "Syzygy": { disk: "syzygy 18k file PRODOS (san inc pack)", prelaunch: "syzygy" },
  "Talon": { disk: "talon PRODOS (san inc pack)", prelaunch: "talon" },
  "Tapper": { disk: "Tapper PRODOS (san inc pack)", prelaunch: "tapper" },
  "Technocop": { disk: "technocop PRODOS (san inc pack)", prelaunch: "technocop" },
  "Teleport": { disk: "teleport PRODOS (san inc crack)", prelaunch: "teleport" },
  "Tetris": { disk: "tetris PRODOS (san inc crack)", prelaunch: "standard" },
  "Tharolian Tunnels": { disk: "tharolian tunnels PRODOS (san inc pack)", prelaunch: "tharolian.tunls" },
  "The Asteroid Field": { disk: "the asteroid field 7k file PRODOS (san inc pack)", prelaunch: "asteroid.field" },
  "The Bilestoad": { disk: "the bilestoad 22k file PRODOS (san inc pack)", prelaunch: "standard" },
  "The Caverns of Freitag": { disk: "the caverns of freitag 17k file PRODOS (san inc pack)", prelaunch: "caverns.freitag" },
  "The Chase on Tom S's Island": { disk: "The Chase on Tom Sawyer's Island PRODOS (san inc pack)", prelaunch: "tom.sawyer" },
  "The Goonies": { disk: "goonies PRODOS (san inc pack)", prelaunch: "the.goonies" },
  "The Heist": { disk: "the heist PRODOS (san inc pack)", prelaunch: "the.heist" },
  "The Human Fly": { disk: "the human fly 15k file PRODOS (san inc pack)", prelaunch: "the.human.fly" },
  "The Last Gladiator": { disk: "the last gladiator PRODOS (san inc pack)", prelaunch: "last.gladiator" },
  "The Last Ninja": { disk: "the last ninja PRODOS (san inc crack)", prelaunch: "the.last.ninja" },
  "The Movie Monster Game": { disk: "the movie monster game PRODOS (san inc pack)", prelaunch: "movie.monster" },
  "The Snapper": { disk: "the snapper 9k file PRODOS (san inc crack)", prelaunch: "the.snapper" },
  "The Space Ark": { disk: "the space ark PRODOS (san inc crack)", prelaunch: "the.space.ark" },
  "The Spy Strikes Back": { disk: "the spy strikes back 10k file PRODOS (san inc pack)", prelaunch: "spy.strikes.bak" },
  "The Voyage of the Valkyrie": { disk: "the voyage of the valkyrie PRODOS (san inc pack)", prelaunch: "voyage.valkyrie" },
  "Thexder": { disk: "thexder PRODOS (san inc pack)", prelaunch: "thexder" },
  "Thief": { disk: "thief 7k file PRODOS (san inc pack)", prelaunch: "thief" },
  "Threshold": { disk: "threshold PRODOS (san inc pack)", prelaunch: "threshold" },
  "Thunder Bombs": { disk: "thunder bombs 14k file PRODOS (san inc pack)", prelaunch: "thunder.bombs" },
  "Thunderbird GX": { disk: "thunderbird gx 4k file PRODOS (san inc pack)", prelaunch: "thunderbird.gx" },
  "Time Pilot": { disk: "time pilot 15k file PRODOS (san inc pack)", prelaunch: "time.pilot" },
  "Time Tunnels": { disk: "time tunnels 12k file PRODOS (san inc pack)", prelaunch: "time.tunnels" },
  "Titan Cronus": { disk: "titan cronus 6k file PRODOS (san inc pack)", prelaunch: "titan.cronus" },
  "Torax": { disk: "torax 6k file PRODOS (san inc pack)", prelaunch: "torax" },
  "Torpedo Terror": { disk: "torpedo terror 15k file PRODOS (san inc pack)", prelaunch: "torpedo.terror" },
  "Track Attack": { disk: "track attack PRODOS (san inc crack)", prelaunch: "track.attack" },
  "Treasure Dive": { disk: "treasure dive 5k file PRODOS (san inc pack)", prelaunch: "treasure.dive" },
  "Triad": { disk: "triad 18k file PRODOS (san inc pack)", prelaunch: "triad" },
  "Trolls and Tribulations": { disk: "trolls and tribulations 19k file PRODOS (san inc pack)", prelaunch: "trolls.tribs" },
  "Trompers": { disk: "trompers 10k file PRODOS (san inc pack)", prelaunch: "trompers" },
  "Tsunami": { disk: "tsunami 10k file PRODOS (san inc pack)", prelaunch: "tsunami" },
  "Tubeway ][": { disk: "tubeway 18k file PRODOS (san inc pack)", prelaunch: "tubeway" },
  "Tunnel Terror": { disk: "tunnel terror 20k file PRODOS (san inc pack)", prelaunch: "tunnel.terror" },
  "Twerps": { disk: "twerps 14k file PRODOS (san inc crack)", prelaunch: "twerps" },
  "Up'n Down": { disk: "up'n down PRODOS (san inc pack)", prelaunch: "up.n.down" },
  "Victory Road": { disk: "victory road PRODOS (san inc pack)", prelaunch: "victory.road" },
  "Vindicator": { disk: "vindicator PRODOS (san inc crack)", prelaunch: "vindicator" },
  "Viper": { disk: "viper 6kb file PRODOS (san inc pack)", prelaunch: "viper" },
  "Viper Patrol": { disk: "viper patrol 17k file and rod's revenge 16k file PRODOS (san inc pack)", prelaunch: "viper.patrol" },
  "Vortex": { disk: "vortex 7k file PRODOS (san inc pack)", prelaunch: "vortex" },
  "Wall Defence": { disk: "wall defence 1k file PRODOS (san inc pack)", prelaunch: "wall.defence" },
  "Wargle": { disk: "wargle PRODOS (san inc pack)", prelaunch: "wargle" },
  "Warp Destroyer": { disk: "warp destroyer PRODOS (san inc crack)", prelaunch: "warp.destroyer" },
  "Wavy Navy": { disk: "wavy navy 18k file PRODOS (san inc pack)", prelaunch: "wavy.navy" },
  "Wayout": { disk: "wayout PRODOS (san inc crack)", prelaunch: "wayout" },
  "Who Framed Roger Rabbit": { disk: "who framed roger rabbit PRODOS (san inc crack)", prelaunch: "roger.rabbit" },
  "Whomper Stomper": { disk: "whomper stomper 16k file PRODOS (san inc pack)", prelaunch: "whomper.stomper" },
  "Willy Byte": { disk: "willy byte PRODOS (san inc pack)", prelaunch: "willy.byte" },
  "Wings of Fury": { disk: "wings of fury PRODOS (san inc crack)", prelaunch: "wings.of.fury" },
  "Xevious": { disk: "xevious 24k file PRODOS (san inc pack)", prelaunch: "xevious" },
  "Yewdow": { disk: "yewdow (4am pack)", prelaunch: "yewdow" },
  "Zargs": { disk: "zargs 19k file PRODOS (san inc pack)", prelaunch: "zargs" },
  "Zaxxon": { disk: "zaxxon Mockingboard PRODOS (san inc pack)", prelaunch: "zaxxon" },
  "Zenith": { disk: "zenith 17k file PRODOS (san inc crack)", prelaunch: "zenith" },
  "Zero Gravity Pinball": { disk: "zero gravity pinball 13k file PRODOS (san inc crack)", prelaunch: "zp" },
  "Zoo Master": { disk: "zoo master PRODOS (san inc pack)", prelaunch: "zoo.master" },
}

// ---------------------------------------------------------------------------
// 4cade prelaunch support — fetch, parse, extract
// ---------------------------------------------------------------------------

/** A single operation in the packed binary launch sequence. */
export type PrelaunchOp =
  | { op: "patch"; addr: number; val: number }   // LDA #val; STA addr
  | { op: "call"; addr: number }                  // JSR addr
  | { op: "decompress"; addr: number }            // JSR to decompressor entry
  | { op: "readRom" }                             // STA $C082 — LC read ROM, no write
  | { op: "rwRam2" }                              // BIT $C083; BIT $C083 — LC read/write RAM bank 2
  | { op: "rdRam2" }                              // STA $C080 — LC read RAM bank 2, no write
  | { op: "callback_vector"; loAddr: number; hiAddr: number }  // store callback address at loAddr/hiAddr
  | { op: "jmp_decompress"; addr: number }        // JMP to decompressor (callback-based, no return)
  | { op: "reset_vector" }                        // install trailing stack-page reset handler in $3F2 and LC $FFFC
  | { op: "reset_handler"; mode: "rdRam2" }       // install named stack-page reset handler in $3F2
  | { op: "install_routine"; loAddr: number; hiAddr: number; bytes: number[] }

/** Runtime prelaunch data parsed from a fetched .a file. */
export type PrelaunchEntry = number | "loadAddress" | { indirect: number }

export type ParsedPrelaunch = {
  sequence: PrelaunchOp[]
  entry: PrelaunchEntry
}

const FOUR_CADE_BASE_URL = "https://raw.githubusercontent.com/a2-4am/4cade/v6.0.1"

/** Fetch the compressed .po disk from the 4cade repo.  Returns raw bytes. */
export const fetchFourCadeDisk = async (entry: FourCadeEntry): Promise<Uint8Array> => {
  const url = `${FOUR_CADE_BASE_URL}/res/dsk/${encodeURIComponent(entry.disk + ".po")}`
  const resp = await fetch(url)
  if (!resp.ok) throw new Error(`Failed to fetch 4cade disk "${entry.disk}": ${resp.status}`)
  return new Uint8Array(await resp.arrayBuffer())
}

/** Fetch the prelaunch assembly source from the 4cade repo. */
export const fetchFourCadePrelaunch = async (entry: FourCadeEntry): Promise<string> => {
  const url = `${FOUR_CADE_BASE_URL}/src/prelaunch/${encodeURIComponent(entry.prelaunch + ".a")}`
  const resp = await fetch(url)
  if (!resp.ok) throw new Error(`Failed to fetch 4cade prelaunch "${entry.prelaunch}": ${resp.status}`)
  return resp.text()
}

/**
 * Parse a 4cade prelaunch .a file into a sequence of operations.
 */
export const parsePrelaunchScript = (source: string): ParsedPrelaunch | undefined => {
  const ops: PrelaunchOp[] = []
  let entry: PrelaunchEntry | undefined
  let hasDecompress = false
  let pendingLdaVal: number | undefined
  let parsingResetVector = false
  let sawMachineStatus = false
  let sawCheatsMask = false
  let skippingCheatBlock = false

  if (source.includes("!pseudopc")) return undefined

  const sourceWithoutComments = source
    .split(/\r?\n/)
    .map((line) => line.replace(/;.*$/, ""))
    .join("\n")
  const hasCanonicalResetVector =
    /lda\s+#<reset\b[\s\S]*?sta\s+\$3F2\b[\s\S]*?sta\s+\$FFFC\b[\s\S]*?lda\s+#>reset\b[\s\S]*?sta\s+\$3F3\b[\s\S]*?sta\s+\$FFFD\b[\s\S]*?eor\s+#\$A5\b[\s\S]*?sta\s+\$3F4\b/i.test(sourceWithoutComments) &&
    /^\s*reset\b:?\s*\n\s*\+READ_ROM_NO_WRITE\b\s*\n\s*inc\s+\$3F4\b\s*\n\s*jmp\s+\(\s*\$FFFC\s*\)/im.test(sourceWithoutComments)
  const hasReadRam2ResetHandler =
    /^\s*reset\b:?\s*\n\s*\+READ_RAM2_NO_WRITE\b\s*\n\s*jmp\s+\(\s*\$FFFC\s*\)/im.test(sourceWithoutComments)
  const dualCallbackSetup = sourceWithoutComments.match(
    /lda\s+#<callback1\b\s*\n\s*sta\s+\$([0-9a-f]{2,4})\b\s*\n\s*lda\s+#>callback1\b\s*\n\s*sta\s+\$([0-9a-f]{2,4})\b\s*\n\s*lda\s+#<callback2\b\s*\n\s*sta\s+\$([0-9a-f]{2,4})\b\s*\n\s*lda\s+#>callback2\b\s*\n\s*sta\s+\$([0-9a-f]{2,4})\b/i,
  )
  const hasDualArithmeticCallbackBodies =
    /^\s*callback1\b:?\s*\n\s*sec\b\s*\n\s*sbc\s+#8\b\s*\n\s*cmp\s+#2\b\s*\n\s*bcc\s+\+\s*\n\s*-\s*jmp\s+\$AE0A\b\s*\n\s*\+\s*jmp\s+\$ADF9\b/im.test(sourceWithoutComments) &&
    /^\s*callback2\b:?\s*\n\s*sec\b\s*\n\s*sbc\s+#8\b\s*\n\s*cmp\s+#2\b\s*\n\s*bcs\s+-\s*\n\s*jmp\s+\$AE21\b/im.test(sourceWithoutComments)

  // Callback detection state — handles decompressors that JMP to a routine
  // which calls back into the prelaunch code after decompression (e.g. Frogger).
  let callbackLoAddr: number | undefined
  let callbackHiAddr: number | undefined
  let pendingCallbackLo = false
  let pendingCallbackHi = false
  let inCallbackBody = false

  const lines = source.split(/\r?\n/)
  for (const rawLine of lines) {
    const line = rawLine.replace(/;.*$/, "").trim()
    if (!line) continue
    if (line.startsWith("!") || line.startsWith("*=")) continue

    if (skippingCheatBlock) {
      if (line === "+") skippingCheatBlock = false
      continue
    }
    if (line.match(/^\+GET_MACHINE_STATUS(?:_LC_RW)?\b/i)) {
      sawMachineStatus = true
      continue
    }
    if (line.match(/^lda\s+MachineStatus\b/i)) {
      sawMachineStatus = true
      pendingLdaVal = undefined
      continue
    }
    if (sawMachineStatus && line.match(/^and\s+#CHEATS_ENABLED\b/i)) {
      sawCheatsMask = true
      continue
    }
    if (sawCheatsMask && line.match(/^beq\s+\+\s*$/i)) {
      skippingCheatBlock = true
      sawMachineStatus = false
      sawCheatsMask = false
      continue
    }

    if (parsingResetVector) {
      if (line.match(/^sta\s+\$3F4\b/i)) parsingResetVector = false
      continue
    }

    // Detect callback label (e.g. "callback" or "callback:" on its own line)
    if (line.match(/^callback\b:?$/i)) { inCallbackBody = true; continue }

    // In callback body: skip JSR and instruction-level lines (they may include
    // ProDOS MLI calls with inline parameters we can't reproduce).  Only process
    // recognized macros which provide essential cleanup (DISABLE_ACCEL, etc.).
    if (inCallbackBody) {
      if (line.match(/^rts\b/i)) break  // end of callback
      // Only process + macros in callback body (they're handled below)
      if (!line.startsWith("+")) { pendingLdaVal = undefined; continue }
    }

    // 4cade macro expansions — must match acme macros in src/macros.a exactly.
    // LC bank 2 function addresses: EnableAccelerator=$DFB7, DisableAccelerator=$DFB4,
    // HideLaunchArtworkLC2=$DFAE (all in LC bank 2, stubbed to RTS in our relay).
    if (line.match(/^\+ENABLE_ACCEL_LC\b/)) { ops.push({ op: "rwRam2" }, { op: "call", addr: 0xDFB7 }); continue }
    if (line.match(/^\+ENABLE_ACCEL_AND_HIDE_ARTWORK_LC\b/)) { ops.push({ op: "rwRam2" }, { op: "call", addr: 0xDFB7 }, { op: "call", addr: 0xDFAE }); continue }
    if (line.match(/^\+ENABLE_ACCEL_AND_HIDE_ARTWORK\b/)) { ops.push({ op: "rwRam2" }, { op: "call", addr: 0xDFB7 }, { op: "call", addr: 0xDFAE }, { op: "readRom" }); continue }
    if (line.match(/^\+ENABLE_ACCEL\b/)) { ops.push({ op: "rwRam2" }, { op: "call", addr: 0xDFB7 }, { op: "readRom" }); continue }
    if (line.match(/^\+DISABLE_ACCEL_AND_HIDE_ARTWORK_LC\b/)) { ops.push({ op: "call", addr: 0xDFB4 }, { op: "call", addr: 0xDFAE }, { op: "readRom" }); continue }
    if (line.match(/^\+DISABLE_ACCEL_AND_HIDE_ARTWORK\b/)) { ops.push({ op: "rwRam2" }, { op: "call", addr: 0xDFB4 }, { op: "call", addr: 0xDFAE }, { op: "readRom" }); continue }
    if (line.match(/^\+DISABLE_ACCEL_LC\b/)) { ops.push({ op: "call", addr: 0xDFB4 }, { op: "readRom" }); continue }
    if (line.match(/^\+DISABLE_ACCEL\b/)) { ops.push({ op: "rwRam2" }, { op: "call", addr: 0xDFB4 }, { op: "readRom" }); continue }
    if (line.match(/^\+HIDE_ARTWORK_LC\b/)) { ops.push({ op: "call", addr: 0xDFAE }, { op: "readRom" }); continue }
    if (line.match(/^\+HIDE_ARTWORK\b/)) { ops.push({ op: "rdRam2" }, { op: "call", addr: 0xDFAE }, { op: "readRom" }); continue }
    if (line.match(/^\+READ_ROM_NO_WRITE\b/)) { ops.push({ op: "readRom" }); continue }
    if (line.match(/^\+READ_RAM2_WRITE_RAM2\b/)) { ops.push({ op: "rwRam2" }); continue }
    if (line.match(/^\+READ_RAM2_NO_WRITE\b/)) { ops.push({ op: "rdRam2" }); continue }
    if (hasReadRam2ResetHandler && line.match(/^\+RESET_VECTOR\s+reset\b/i)) {
      ops.push({ op: "reset_handler", mode: "rdRam2" })
      continue
    }
    if (line.startsWith("+")) continue

    if (hasCanonicalResetVector && line.match(/^lda\s+#<reset\b/i)) {
      ops.push({ op: "reset_vector" })
      parsingResetVector = true
      pendingLdaVal = undefined
      continue
    }

    // Detect callback address setup: lda #<callback / lda #>callback
    if (line.match(/^lda\s+#<\w+/i)) { pendingCallbackLo = true; pendingLdaVal = undefined; continue }
    if (line.match(/^lda\s+#>\w+/i)) { pendingCallbackHi = true; pendingLdaVal = undefined; continue }

    const ldaHexMatch = line.match(/^lda\s+#\$([0-9a-fA-F]{1,2})\b/i)
    if (ldaHexMatch) { pendingLdaVal = parseInt(ldaHexMatch[1], 16); continue }
    const ldaDecMatch = line.match(/^lda\s+#(\d+)\b/i)
    if (ldaDecMatch) { pendingLdaVal = parseInt(ldaDecMatch[1], 10) & 0xFF; continue }

    const staMatch = line.match(/^sta\s+\$([0-9a-fA-F]{2,4})\b/i)
    if (staMatch) {
      const addr = parseInt(staMatch[1], 16)
      if (pendingCallbackLo) { callbackLoAddr = addr; pendingCallbackLo = false; continue }
      if (pendingCallbackHi) { callbackHiAddr = addr; pendingCallbackHi = false; continue }
      if (pendingLdaVal !== undefined) {
        ops.push({ op: "patch", addr, val: pendingLdaVal })
        continue
      }
    }

    const jsrMatch = line.match(/^jsr\s+\$([0-9a-fA-F]{2,4})\b/i)
    if (jsrMatch) {
      pendingLdaVal = undefined
      const addr = parseInt(jsrMatch[1], 16)
      if (!hasDecompress) { hasDecompress = true; ops.push({ op: "decompress", addr }) }
      else { ops.push({ op: "call", addr }) }
      continue
    }

    const indirectJmpMatch = line.match(/^jmp\s+\(\s*([^)]+?)\s*\)/i)
    if (indirectJmpMatch) {
      const target = indirectJmpMatch[1].trim()
      if (target.toLowerCase() === "ldrlo2") {
        entry = "loadAddress"
      } else {
        const targetMatch = target.match(/^\$([0-9a-fA-F]{1,4})$/)
        if (!targetMatch) return undefined
        entry = { indirect: parseInt(targetMatch[1], 16) }
      }
      break
    }

    const jmpMatch = line.match(/^jmp\s+\$([0-9a-fA-F]{2,4})\b/i)
    if (jmpMatch) {
      const addr = parseInt(jmpMatch[1], 16)
      // Callback-based decompress: JMP before any JSR decompress, with callback vector set
      if (!hasDecompress && callbackLoAddr !== undefined && callbackHiAddr !== undefined) {
        ops.push({ op: "callback_vector", loAddr: callbackLoAddr, hiAddr: callbackHiAddr })
        ops.push({ op: "jmp_decompress", addr })
        hasDecompress = true
        continue  // don't break — callback body follows
      }
      entry = addr
      break
    }

    pendingLdaVal = undefined
  }

  // Callback-based prelaunches have no explicit entry — the decompressor handles it.
  // Use entry = -1 to signal this to the relay generator.
  if (entry === undefined && inCallbackBody) entry = -1
  if (entry === undefined) return undefined
  if (!hasDecompress && ops.length === 0) return undefined
  if (dualCallbackSetup && hasDualArithmeticCallbackBodies) {
    ops.push({
      op: "install_routine",
      loAddr: parseInt(dualCallbackSetup[1], 16),
      hiAddr: parseInt(dualCallbackSetup[2], 16),
      bytes: [0x38, 0xE9, 0x08, 0xC9, 0x02, 0x90, 0x03, 0x4C, 0x0A, 0xAE, 0x4C, 0xF9, 0xAD],
    })
    ops.push({
      op: "install_routine",
      loAddr: parseInt(dualCallbackSetup[3], 16),
      hiAddr: parseInt(dualCallbackSetup[4], 16),
      bytes: [0x38, 0xE9, 0x08, 0xC9, 0x02, 0x90, 0x03, 0x4C, 0x0A, 0xAE, 0x4C, 0x21, 0xAE],
    })
  }
  return { sequence: ops, entry }
}

/**
 * Extract the packed binary and its load address from a 4cade .po disk.
 * The main game binary is the first non-system file in the ProDOS directory.
 */
export const extractPackedBinary = (poData: Uint8Array): { data: Uint8Array; loadAddress: number } | undefined => {
  const files = extractAllBinFiles(poData)
  return files.length > 0 ? files[0] : undefined
}

/**
 * Extract ALL non-system BIN files from a 4cade .po disk.
 * Returns them in directory order. The first is the main packed binary;
 * additional entries are supplementary files (title screen, game code, etc.)
 * that the game's loader would read from disk via ProDOS MLI calls.
 */
export const extractAllBinFiles = (poData: Uint8Array): Array<{ data: Uint8Array; loadAddress: number; name: string }> => {
  const results: Array<{ data: Uint8Array; loadAddress: number; name: string }> = []
  const blockSize = 512
  const block2off = 2 * blockSize
  if (poData.length < block2off + blockSize) return results

  const volByte = poData[block2off + 4]
  if (((volByte >> 4) & 0xF) !== 0xF) return results
  const entryLength = poData[block2off + 4 + 0x1F] || 0x27

  let dirBlock = 2
  for (let pass = 0; pass < 20 && dirBlock > 0; pass++) {
    const off = dirBlock * blockSize
    if (off + blockSize > poData.length) break
    const startEntry = pass === 0 ? off + 4 + entryLength : off + 4
    for (let e = startEntry; e + entryLength <= off + blockSize; e += entryLength) {
      const st = (poData[e] >> 4) & 0xF
      if (st === 0 || st === 0xF) continue
      const nameLen = poData[e] & 0xF
      if (nameLen === 0) continue
      const name = String.fromCharCode(...poData.slice(e + 1, e + 1 + nameLen))
      if (name === "PRODOS" || name.endsWith(".SYSTEM")) continue

      const fileType = poData[e + 0x10]
      const keyBlock = poData[e + 0x11] | (poData[e + 0x12] << 8)
      const eof = poData[e + 0x15] | (poData[e + 0x16] << 8) | (poData[e + 0x17] << 16)
      const auxType = poData[e + 0x1F] | (poData[e + 0x20] << 8)

      if (fileType !== 0x06) continue
      if (eof === 0) continue

      let fileData: Uint8Array | undefined
      if (st === 1) {
        fileData = poData.slice(keyBlock * blockSize, keyBlock * blockSize + eof)
      } else if (st === 2) {
        const idxOff = keyBlock * blockSize
        const blocks: number[] = []
        for (let i = 0; i < 256; i++) {
          const blk = poData[idxOff + i] | (poData[idxOff + 256 + i] << 8)
          if (blk === 0) break
          blocks.push(blk)
        }
        fileData = new Uint8Array(eof)
        let written = 0
        for (const blk of blocks) {
          const len = Math.min(blockSize, eof - written)
          fileData.set(poData.slice(blk * blockSize, blk * blockSize + len), written)
          written += len
        }
      } else if (st === 3) {
        const masterOff = keyBlock * blockSize
        const fileBytes = new Uint8Array(eof)
        let written = 0
        for (let mi = 0; mi < 128 && written < eof; mi++) {
          const idxBlock = poData[masterOff + mi] | (poData[masterOff + 256 + mi] << 8)
          if (idxBlock === 0) break
          const idxOff = idxBlock * blockSize
          for (let i = 0; i < 256 && written < eof; i++) {
            const blk = poData[idxOff + i] | (poData[idxOff + 256 + i] << 8)
            if (blk === 0) { written += blockSize; continue }
            const len = Math.min(blockSize, eof - written)
            fileBytes.set(poData.slice(blk * blockSize, blk * blockSize + len), written)
            written += len
          }
        }
        fileData = fileBytes
      }

      if (fileData) {
        results.push({ data: fileData, loadAddress: auxType, name })
      }
    }
    dirBlock = poData[off + 2] | (poData[off + 3] << 8)
  }
  return results
}
